# Generated by Django 3.1.2 on 2021-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.CharField(default='default', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('country_name', models.CharField(default='default', max_length=255)),
                ('iata', models.CharField(default='default', max_length=255)),
                ('rank', models.FloatField(default=0.0)),
                ('country_id', models.CharField(default='default', max_length=255)),
                ('con_id', models.CharField(default='default', max_length=255)),
            ],
            options={
                'db_table': 'Cities',
                'managed': True,
            },
        ),
    ]
